### ISSUE TITLE
Using the list in a PropertyDrawer?

### ISSUE THREAD

**Issue by guirimarc** [cfoulston/Unity-Reorderable-List#10]
Is it possible to use the ReordableList inside a PropertyDrawer? I am not using Attributes.

What I'm doing in OnGUI is initializing the ReorderableList with the property and then 'DoList'. However it looks like when I change one item of the list it does the same for all of them.

**Comment by cfoulston** [comment]
If the property you're passing to `ReorderableList` is a `ReorderableArray` you can get a list for the property like this:

```
ReorderableList list = ReorderableDrawer.GetList(property);
list.DoList(listRect, listLabel);
```

If your list does not extend from `ReorderableArray` then you must create a dictionary to hold your list references and access them based on the property. There's a method: `ReorderableDrawer.GetListId` which will return a lookup id for you. save that to a dictionary with a reference to a new `ReorderableList` and things should work out.

Check out the source under `ReorderableDrawer` to see how I've implemented it.
