### ISSUE TITLE
Suggestion: Remove project files from repo

### ISSUE THREAD

**Issue by Siccity** [cfoulston/Unity-Reorderable-List#11]
Since this is a plugin and not a project, it would be beneficial to not include the entire unity project folder in the repo. It would be simpler to navigate, and would allow users to add your plugin as a git submodule directly in their projects.

1) Move Assets/ReorderableList contents to root, and delete the remaining Assets folder
2) Create an issue "screenshots" and post your screenshots there, then remove them from the repo
3) Delete UnityPackageManager/. It seems to not be doing anything anyway

The repo root should then contain the following files/folders:
* Example/
* List/
* Example.meta
* List.meta
* .gitignore
* LICENSE.md
* README.md

I'm not the only one who thinks this is a better approach, here's a fork (not mine) that has done about the same thing.
https://github.com/Cippman/Unity-Reorderable-List

I can send a pull request if you agree with these changes

**Comment by cfoulston** [comment]
I've gone ahead and fixed this.
