### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by MochaMoth** [cfoulston/Unity-Reorderable-List#14]
When used in recursion, after 3 layers, I get a label field that says 'Array must extend from Reorderable Array'. Luckily, the game I'm working on only requires 3 layers, so I can still use it. Would be interesting to look into, though.

![reorderable array recursion code](https://user-images.githubusercontent.com/44219789/47060574-059e9500-d183-11e8-93cf-ec12c492befb.png)
![reorderable array recursion](https://user-images.githubusercontent.com/44219789/47060575-06372b80-d183-11e8-8b16-1ff326824937.png)

**Comment by cfoulston** [comment]
This is a limitation of the Unity serializer. Your code results in a infinite serialization cycle.
You may have noticed a warning similar to this:

"Serialization depth limit 7 exceeded at 'WeatherTable.myTables'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
8: WeatherTable.myTables
7: Malee::ReorderableArray`1.array"

Remove the "Reorderable" attribute and you'll notice you have the same limitations.

Unfortunately there's nothing I can do about this. So I'm closing this issue
