### ISSUE TITLE
Nested list unity lag

### ISSUE THREAD

**Issue by skullflower** [cfoulston/Unity-Reorderable-List#17]
I'm using a nested reorderable list within a reorderable list for my AI editor, something like this:

![image](https://user-images.githubusercontent.com/7890741/59992570-59f6f000-9601-11e9-9c23-9bc7b16a65a3.png)

```
public ActionTrigger[] actions;

[Serializable] 
public class ActionTrigger {
     [Reorderable(paginate = true, pageSize = 1)] public ActionSetList actionSetList;
}

[Serializable]
    public class ActionSet {

}
```

When there are 4+ elements within the nested list, it starts to lag unity significantly. I've tried to tackle this somewhat by enabling paging, but it's still noticeable.

Is there a way to address this?

**Comment by cfoulston** [comment]
Does the issue still occur if you create a CustomEditor for your Actions class?
i.e manually create the ReorderableList?

Also, have you tried profiling the editor to see where the slowdown might be occuring?

If you want to post the full code for your Actions class I can take a look as well

**Comment by skullflower** [comment]
Figured out this was due to all the conditional hiding of attributes I was doing in the nested list. Closing this out, sorry!
