### ISSUE TITLE
New elements added without correct default values.

### ISSUE THREAD

**Issue by YLlywelyn** [cfoulston/Unity-Reorderable-List#19]
When creating a new object with the + button all the fields in the new object are set to the c# default for that type instead of their default values from the class constructor (ints + floats = 0, string = empty, bool = false).

I've tested by adding a field next to the list that is a singular object.  This object is initialised correctly, but the objects in the list are not.  How can I get this working correctly?

![image](https://user-images.githubusercontent.com/7080961/64729800-ce8d4c80-d4d5-11e9-8ce2-60d041412743.png)

**Comment by cfoulston** [comment]
Yes, this is a limitation of the Unity Editor. Values in lists are set to their defaults (AFAIK)
What you can do is listen to the onAdd event, and manually add an item to the list:

```
[CustomEditor(typeof(AudioManager))]
public class AudioManagerEditor : Editor {

	private ReorderableList list;

	void OnEnable() {

		list = new ReorderableList(serializedObject.FindProperty("sounds"));
		list.onAddCallback += OnListAdd;
	}

	private void OnListAdd(ReorderableList list) {

		SerializedProperty property = list.AddItem();

		property.FindPropertyRelative("name").stringValue = "new sound";
		property.FindPropertyRelative("volume").floatValue = 1;
		property.FindPropertyRelative("pitch").floatValue = 1;
	}

	public override void OnInspectorGUI() {

		serializedObject.Update();

		list.DoLayoutList();

		serializedObject.ApplyModifiedProperties();
	}
}
```

If you remove the ReorderableList and just use default Unity array drawer. You should see the same issue occur. Default values not set. Unity has an issue for this: https://issuetracker.unity3d.com/issues/wrong-default-value-for-array-elements-added-in-inspector But I suspect it'll be postponed forever!

**Comment by YLlywelyn** [comment]
Missed the callback, that'll fix it.  Thanks for taking the time 🙂
