### ISSUE TITLE
Possible to use in an editor window?

### ISSUE THREAD

**Issue by MostHated** [cfoulston/Unity-Reorderable-List#20]
Hey there,
   Is it possible to use this in an editor window? I was hoping to use it in a current small project that is using 2017.1.5, but I can't seem to get it. I looked around a bunch and saw that for this type of thing you typically have to use something similar to this:

```cs
		list = serializedObject.FindProperty("list2");
		EditorGUILayout.PropertyField(list, new GUIContent("My List Test"), true);
```
Unfortunately, though, I have been unable to get it working successfully, so I just wanted to see if it was even possible?

Thanks,
-MH

**Comment by cfoulston** [comment]
Yes. But it only supports SerializedProperties. So you would need to manually create a SerializedObject for your EditorWindow, which contains your array data and handle. Something like this (Untested):

```
class MyEditorWindow : EditorWindow {

    [SerializeField] private float[] myArray = new float[0];

    private SerializedObject so;
    private ReorderableList list;

    void OnEnable() {

        so = new SerializedObject(this);

        list = new ReorderableList(so.FindProperty("myArray"));
    }

    void OnDestroy() {

        so.Dispose();
    }

    void OnGUI() {

        so.Update();

        list.DoLayoutList();

        so.ApplyModifiedProperties();
    }
}
```

**Comment by MostHated** [comment]
Great, this worked. Thanks, I appreciate it.

**Comment by MostHated** [comment]
EDIT - I got it all figured out, nevermind!


Sorry, I had one more question about it. I tried to make the list paginated, but I am guessing that it needs to be done a different way in this case?

I attempted to simply do:

```cs
    [SerializeField, Reorderable(paginate = true, pageSize = 5, elementNameProperty = "test")]
    private float[] myArray = new float[0];
```
but there didn't seem to be any sort of change to what was displayed in the window.

In  OnGui() you had:

```cs
    void OnGUI()
    {
      so.Update();
      list.DoLayoutList();
      so.ApplyModifiedProperties();
    }
```
I tried to see if perhaps list.Paginate() existed to I could set it to true, or similar, but I didn't see anything like that either.

I put it on this to test as well:

```cs
    [SerializeField, Reorderable(paginate = true, pageSize = 5, elementNameProperty = "test")]
    private ReorderableList list;
```

but that didn't seem to work either. It made some controls show up, but no pagination.
