### ISSUE TITLE
DrawElementCallback foldout issue

### ISSUE THREAD

**Issue by dps999** [cfoulston/Unity-Reorderable-List#21]
Hi,
I'm using DrawElementCallback to display my custom fields.
But I can't make them appear right when they folded.
Elements unfolded
![image](https://user-images.githubusercontent.com/1697478/70338756-90968f00-185e-11ea-9311-b8e9072311d5.png)
Elements folded
![image](https://user-images.githubusercontent.com/1697478/70338640-55945b80-185e-11ea-9183-7d922dacd14e.png)

private void ElementDraw(Rect position, SerializedProperty property, GUIContent label, bool selected, bool focused)
        {
            position.width = 200; position.height = 20;
            EditorGUI.BeginProperty(position, label, property);
                targetType = property.FindPropertyRelative("type");
                int newselectedTarget = EditorGUI.Popup(position, targetType.intValue, levelData?.GetTargetsNames());
                targetType.intValue = newselectedTarget;
                position.y += 20; 
                EditorGUI.PropertyField(position, property.FindPropertyRelative("count"), GUIContent.none);
            EditorGUI.EndProperty();
        }

**Comment by cfoulston** [comment]
You'll probably want to check "property.isExpanded". And if false, don't draw more than 1 child element.

**Comment by dps999** [comment]
@cfoulston thank you very much!
