### ISSUE TITLE
Inner Array Attributes

### ISSUE THREAD

**Issue by Noeski** [cfoulston/Unity-Reorderable-List#24]
Is there an easy way to add attributes to the inner `array` field in `ReorderableArray`?

So far the options I've come up with are:
1. Use a `List<>` with my own attributes applied and create a custom editor that uses a `ReorderableList`.
2. Create a copy of the `ReorderableArray` class with my own attributes applied.
3. Refactor `ReorderableArray` so that it is extensible i.e. make `array` an abstract property and child classes can apply their own attributes as needed.

I'm curious if you've come across this problem and know of an alternate solution or if one of the above is the best way to go.

**Comment by xiaobin83drpanda** [comment]
I made a class that wraps the original class. then use the new class as the template of ReorderableArray.

```
[Serializable]
private class ActionTypeReferenceList : ReorderableArray<ActionTypeReference> { }

[Serializable]
public class ActionTypeReference
{
	[SerializeField, ClassExtends(typeof(Action), Grouping = ClassGrouping.ByNamespace)]
	private ClassTypeReference _reference
}

```
And i also made a drawer for ActionTypeReference for better look (avoid that collapsing toggle)

**Comment by cfoulston** [comment]
You can use any custom class which contains an "array" property to render as a ReorderableList.
The "ReorderableDrawer", which draws the "Reorderable" attribute simply needs an "array" field to supply the ReorderableList with a SerializedProperty.

so if you want a custom attribute on your array field, I would create your own ReorderableArray class, something like this perhaps:

```
class MyClass : MonoBehaviour {

	[SerializeField, Reorderable] MyArray objects = new MyArray();

	[System.Serializable]
	private class MyArray {

		[SerializeField, SomeCustomAttribute]
		private Object[] array = new Object[0];
	}
}
```

**Comment by Noeski** [comment]
Great, thank you!
