### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [cfoulston/Unity-Reorderable-List#27]
Hi @cfoulston,

Thanks for making this awesome UPM package. I'm the creator of the OpenUPM platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 200+ open-source UPM packages at the time of writing.

To make it happen, I would suggest you make GitHub releases (which create Git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

After your GitHub release, our build pipelines will detect the changes and build UPM packages in 5-10 minutes. Then you can visit your package at https://openupm.com/packages/com.malee.reorderablelist/.

Hopeful this makes sense for you.

**Comment by cfoulston** [comment]
Hi Favoyang. Thanks for this, I've created a release so hopefully will show up on OpenUPM soon

**Comment by favoyang** [comment]
https://openupm.com/packages/com.malee.reorderablelist/

Thanks, it works.
