### ISSUE TITLE
Select Object Popup not working

### ISSUE THREAD

**Issue by InfectedBytes** [cfoulston/Unity-Reorderable-List#29]
Hey man,
great work you're doing!
But I got a little problem with your ReorderableList and Unity's "Select Object" Popup.
If I take your GameObjectExample script as an example, everything works well with drag and drop, but if I want to select the GameObject via the list window, it does not work. Here a little example screenshot:
![image](https://user-images.githubusercontent.com/11035509/98038800-0106b100-1e1e-11eb-9bba-3a44120823d2.png)
When I click on the small circle, a new window pops up. Normally I could just select the GameObject, but from your List it doesn't work. As you can see in the screenshot, I actually already selected another GameObject, but the List content doesn't change.

Any idea on how this could be fixed?
(I use Unity 2019.4.13f1)

**Comment by cfoulston** [comment]
Hey, I think there was an issue Unity solved:
https://issuetracker.unity3d.com/issues/pop-up-windows-like-color-picker-get-closed-when-clicked-immediately-after-opening-it

forum thread:
https://forum.unity.com/threads/object-picker-issues.1008589/

I can't reproduce this issue anymore. Are you still experiencing it?

**Comment by InfectedBytes** [comment]
ah great, yes it seems to be fixed!
