### ISSUE TITLE
Selection of elements of certain types is broken (Vector2, Vector3)

### ISSUE THREAD

**Issue by samloeschen** [cfoulston/Unity-Reorderable-List#3]
Hey there, I can't edit certain types by clicking on them. Unity simply doesn't highlight/activate the field that was clicked on. In this case I am serializing a `ReorderableArray<Vector3>`. I've only been able to replicate the issue with Vector2s and Vector3s - Vector4s work fine, as do single field types such as strings or floats. Maybe this is because Vector4 elements expand? It could have something to do with the fact that the fields for the Vector3 x y z values are on the same area that can be dragged to move the element. I can tab to those fields to highlight and edit them, but that's rather cumbersome. I'm using Unity 5.5.0f3

Thanks for building this! It's speeding up my workflow quite a bit

**Comment by cfoulston** [comment]
I'll get on a fix ASAP. Thanks for Finding

**Comment by cfoulston** [comment]
This should be fixed now.

**Comment by samloeschen** [comment]
Awesome thank you!
