### ISSUE TITLE
Reorderable item force jump to the top

### ISSUE THREAD

**Issue by o-tokar** [cfoulston/Unity-Reorderable-List#30]
I create simple one dimension reorder-list based-on package Example, and Child object with one field 
`public Color[] color;` 
It's happens when I edit colors for any Item in a bottom.

![image](https://user-images.githubusercontent.com/12432871/99390530-745df780-28e1-11eb-9a68-8b0a48f17e7e.png)

**Comment by cfoulston** [comment]
Sorry, I don't quite understand the problem?
