### ISSUE TITLE
Would be great to have a CopyFrom method on ReorderableArray

### ISSUE THREAD

**Issue by bitinn** [cfoulston/Unity-Reorderable-List#7]
Thx to the change for #4, I am able to modify the array at runtime.

But since we often just copy a standard List onto ReorderableArray (which is now also a IList<T>), I would suggest adding a simple `CopyFrom` API that takes a `IList<T>`, and one might do:

```
public IList<SomeObject> CustomArray
{
    get { return _customArray; }
    set { _customArray.CopyFrom(value); }
}
``` 

This is completely do-able in userland, so just a suggestion for enhancement.

Same idea is also present at https://github.com/azixMcAze/Unity-SerializableDictionary

(by the way, my use case is actually exposing this property to editor script, which allows me to migrate values from a List field to ReorderableArray<T> field, as I couldn't find a way to use FormerlySerializedAsAttribute to automate this process.)

**Comment by cfoulston** [comment]
Thanks for the suggestion. I've added this in the latest version

**Comment by bitinn** [comment]
oh thx i should have closed this then :)
