### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by JohannesMP** [cfoulston/Unity-Reorderable-List#9]
It would be useful to have the option to paginate the in-editor view of a reorderable list. 

For example (and this could be hardcoded), only 100 entries are shown, and if there are more a small page UI is visible next to the +/- at the bottom, which shows "page X / Y" where X is editable by the user.

With 315 entries you would by default see "Page 1 of 4" with the first 3 pages having 100 elements visible and page 4 only 15 entries.

Optionally there could also be an input field for 'elements per page' or 'page size'

**Comment by cfoulston** [comment]
Yeah I like this idea. Could add some properties to the list such as:

list.pagination = true
list.pageSize = 100 //0 for custom pagination (UI controlled)

**Comment by cfoulston** [comment]
Hey @JohannesMP I've added pagination into the list. I still need to document it but the usage is simple:

for the attribute version: 
[Reorderable(paginate = true, pageSize = 0)] 

for the object version:
list.paginate = true
list.pageSize = 0

When pageSize = 0, custom pagination is used.
You can also right-click elements and move them to different pages if desired.

Let me know what you think, and if you find any bugs.

**Comment by camblomquist** [comment]
It appears that it's impossible to do anything with pagination if the callbacks are implemented. To give an example: If I were to subscribe to OnAddCallback, there is no apparent way to move to the next page if the new element is not on the current page like it would in AddItem().

**Comment by cfoulston** [comment]
You're right. I've added some public methods to hopefully help with this.
SetPage
SetPageByIndex
GetPage
GetPageByIndex
